// Standard conventions applied to EVERY generated project, so the output is
// consistent and reviewable regardless of provider (OpenAI or Anthropic).
export const CONVENTIONS = `PROJECT CONVENTIONS (follow these in every file, every project):

Stack & structure:
- Node.js 20+, ES modules ("type": "module" in package.json).
- Standard layout:
    src/            application source
      config/       configuration loaded from environment (dotenv)
      routes/       HTTP routes / CLI commands (entry surfaces)
      services/     business logic
      models/       data models / schemas
      utils/        shared helpers
    tests/          automated tests
    package.json, README.md, .env.example, .gitignore
- One responsibility per module; clear named exports; no dead code.

Quality:
- Real, complete implementations — never stubs, TODOs, or "..." placeholders.
- Validate input at boundaries; handle errors with try/catch around async I/O.
- Configuration & secrets come from environment variables (dotenv), never hardcoded.
- package.json MUST have a runnable "test" script that runs ONCE and exits — never
  a watch mode. Prefer Node's built-in test runner: "test": "node --test" (no extra
  deps). If you use vitest, the script MUST be "vitest run" (never bare "vitest",
  which watches and hangs); add vitest to devDependencies. Include at least one
  meaningful test per feature, and the tests must pass.
- README documents what it is, setup, and usage. .env.example lists required vars.

Authorship:
- The work must read as written by a human developer. Never mention AI, Claude,
  OpenAI, language models, or "auto-generated"/"generated by" anywhere — not in
  code, comments, commit messages, README, or docs.`;
